function js_struct = johnson_su_struct(param)
js_struct = struct('Gamma', param(1), ...
                   'Delta', param(2), ...
                   'Lambda', param(3), ...
                   'Xi', param(4));
