function [end1, end2] = LognormalEnds(v, q, g0)
% options = optimset('GradObj','on', 'MaxFunEvals', 2000, ...
%                    'MaxIter', 1000, 'Hessian','user-supplied');
options = optimset('GradObj','on', 'MaxFunEvals', 2000, 'MaxIter', 1000);

[G1, end1] = fmincon(@(X) LognormalEndsFun2(X, v, q, 1),...
                     [real(g0); imag(g0)], [], [], [], [], ...
                     [-15, -Inf], [15; -1.0e-3], ...
                     @(X) LognormalEndsFun1(X, v, q, 0), options);

[G2, end2] = fmincon(@(X) LognormalEndsFun2(X, v, q, -1),...
                     [real(g0); imag(g0)], [], [], [], [], ...
                     [-15, -Inf], [15; -1.0e-3], ...
                     @(X) LognormalEndsFun1(X, v, q, end1), options);

end2 = -end2;

