CC := g++
srcdir := .
objdir := obj

# src := prog1.cpp
# objs := $(notdir $(patsubst %.cpp, %.o, $(srcs)))
# objs := $(addprefix $(objdir)/, $(objs))

CPPFLAGS := -std=c++11 -Wall -g3
LDFLAGS := -lm -larmadillo -lgsl -lgslcblas


