function [mu, sig, sk, kts] = johnson_su_moments(gm, delta, xi, ...
                                                 lambda)
w = exp(1 ./ sig.^2);
Omega = gm ./ delta;

mu = -w.^(1/2) .* sinh(Omega) .* lambda + xi;
sig = sqrt(0.5 * (w-1) .* (w.*cosh(2*Omega) + 1)) .* lambda;
sk = - sqrt(0.5 * w .* (w-1)) .* (...
     w .* (w + 2) .* sinh(3*Omega) + 3*sinh(Omega)) ./ ...
     (w .* cosh(2*Omega) + 1).^1.5;
kts = (w.^2 .* (w.^4 + 2*w.^3 + 3*w.^2 - 3) .* cosh(4*Omega)...
      + 4 * w.^2 .* (w+2) .* cosh(2*Omega) + 3*(2*w + 1)) ./...
      (2 * (w .* cosh(2*Omega) + 1).^2);
